export const bookList = [
  {
    id: 1,
    title: 'Clean Code',
    author: 'Robert C. Martin',
    stock: 10,
    description: 'A guide to writing clean and maintainable code.',
  },
  {
    id: 2,
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt',
    stock: 5,
    description: 'A timeless guide to becoming a pragmatic programmer.',
  },
  {
    id: 3,
    title: 'JavaScript: The Good Parts',
    author: 'Douglas Crockford',
    stock: 8,
    description: 'A deep dive into the most essential features of JavaScript.',
  },
  {
    id: 4,
    title: 'Design Patterns: Elements of Reusable Object-Oriented Software',
    author: 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
    stock: 3,
    description: 'Classic book on software design patterns and object-oriented design.',
  },
  {
    id: 5,
    title: 'Refactoring: Improving the Design of Existing Code',
    author: 'Martin Fowler',
    stock: 7,
    description: 'Guidelines for improving code structure and design.',
  },
  {
    id: 6,
    title: "You Don't Know JS",
    author: 'Kyle Simpson',
    stock: 4,
    description: 'A deep exploration of JavaScript and its quirks.',
  },
  {
    id: 7,
    title: 'The Mythical Man-Month',
    author: 'Fred Brooks',
    stock: 6,
    description: 'A collection of essays on software engineering and project management.',
  },
  {
    id: 8,
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein',
    stock: 12,
    description: 'A comprehensive textbook on algorithms and data structures.',
  },
  {
    id: 9,
    title: 'Code Complete',
    author: 'Steve McConnell',
    stock: 9,
    description: 'A detailed guide to writing high-quality software.',
  },
  {
    id: 10,
    title: 'The Art of Computer Programming',
    author: 'Donald E. Knuth',
    stock: 2,
    description: 'An in-depth exploration of algorithms and programming techniques.',
  },
  {
    id: 11,
    title: 'The Clean Coder',
    author: 'Robert C. Martin',
    stock: 11,
    description: 'Advice on becoming a professional software developer and maintaining discipline.',
  },
  {
    id: 12,
    title: 'The Pragmatic Programmer: Your Journey to Mastery',
    author: 'David Thomas, Andy Hunt',
    stock: 3,
    description: 'An updated version of the classic guide for mastering software development.',
  },
  {
    id: 13,
    title: 'JavaScript: The Definitive Guide',
    author: 'David Flanagan',
    stock: 7,
    description: 'An authoritative reference for JavaScript programming.',
  },
  {
    id: 14,
    title: 'Eloquent JavaScript',
    author: 'Marijn Haverbeke',
    stock: 5,
    description: 'An engaging book to learn JavaScript in depth.',
  },
  {
    id: 15,
    title: 'The Clean Architecture',
    author: 'Robert C. Martin',
    stock: 8,
    description: 'Principles for building maintainable and scalable software architectures.',
  },
  {
    id: 16,
    title: 'Learning JavaScript Design Patterns',
    author: 'Addy Osmani',
    stock: 6,
    description: 'A practical guide to using design patterns in JavaScript.',
  },
  {
    id: 17,
    title: 'Node.js Design Patterns',
    author: 'Mario Casciaro',
    stock: 10,
    description: 'A guide to building efficient and scalable applications using Node.js.',
  },
  {
    id: 18,
    title: "Soft Skills: The Software Developer's Life Manual",
    author: 'John Sonmez',
    stock: 4,
    description: 'A guide to thriving in the software development profession.',
  },
  {
    id: 19,
    title: "The Complete Software Developer's Career Guide",
    author: 'John Sonmez',
    stock: 3,
    description: 'Comprehensive advice on building a successful career in software development.',
  },
  {
    id: 20,
    title: 'Continuous Delivery',
    author: 'Jez Humble, David Farley',
    stock: 7,
    description: 'A guide to delivering software rapidly and reliably.',
  },
];
